course = "                Python Programming                                   "
# print(course.upper())
# print(course.lower())
# print(course.title())
# print(course.rstrip())
# print(course.lstrip())
# print(course.find("P"))
# print(course.replace("p", "J"))
print("Kilode" not in course)
print("Pyt" in course)
